name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-macos:
    runs-on: macos-13

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Update Cargo.toml
        run: |
          sed -i '' "s/^version = \".*\"/version = \"$VERSION\"/" src-tauri/Cargo.toml

      - name: Update tauri.conf.json
        run: |
          jq ".package.version = \"$VERSION\"" src-tauri/tauri.conf.json > tmp.json
          mv tmp.json src-tauri/tauri.conf.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ui

      - name: Build frontend
        run: npm run build
        working-directory: ui

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri app
        run: cargo tauri build -- --release
        working-directory: src-tauri

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: src-tauri/target/release/bundle/macos/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
